### ISSUE TITLE
Could you please upload docker file?

### ISSUE THREAD

**Issue by tom919654** [KAIST-Visual-AI-Group/PDS#1]
Anaconda environment file doesn't work well. I'll be very appreciate if you upload the docker file.

**Comment by 63days** [comment]
Dear tom919654,
First of all, sorry for the late reply.

We've updated the documentations and required dependencies. Could you check out our updated documents again?

(+ We've also added the code for 3D Gaussian Splatting editing!)

Let me know if there are still any issues.

Thanks,
Juil Koo

**Comment by tom919654** [comment]
Thank you!!

**Comment by tom919654** [comment]
Thank you! It works well
