### ISSUE TITLE
Link failure

### ISSUE THREAD

**Issue by jly0810** [KAIST-Visual-AI-Group/PDS#4]
The link to download data and checkpoint below is invalid：
https://kaistackr-my.sharepoint.com/:f:/g/personal/63days_kaist_ac_kr/EocMB6MBpMJJksILj5_C7TYBsU5MCtKS7Wi8FCjlncLnug?e=TTUJZc

**Comment by 63days** [comment]
Dear jiy0810,

It seems the link was broken since my previous personal drive expired. 
Thank you for letting me know.

I've updated the link.
Could you check if it works?

Best,
Juil Koo

**Comment by 63days** [comment]
Since it appears the link is now working properly, I will close the issue.
Thanks.
