### ISSUE TITLE
debug and modify model

### ISSUE THREAD

**Issue by jly0810** [KAIST-Visual-AI-Group/PDS#5]
Your work is built on nerfstudio. I am full of doubts about this because it does not have a main function entry like regular projects and can be easily debugged on pychar or VScode. I would like to ask you how to debug your work? I want to modify the virtual camera to off axis shooting mode during the inference phase (i.e. add an offset to the constructed light), how can I modify it in the code?

**Comment by 63days** [comment]
Hi, jiy0810.
Sorry for getting back to you late.

If you're looking to explore the NeRFStudio code from our codebase, like go-to-definition, you can set the environment variable `export PYTHONPATH=$PYTHON_PATH:YOUR_LOCAL_NERFSTUDIO_DIR_PATH`. This will allow your editor to reference the NeRFStudio code directory. 

For more details on how NeRFstudio code works, you can refer to their documentation: https://github.com/nerfstudio-project/nerfstudio/.

Thanks,
Juil Koo
