### ISSUE TITLE
About Two Implementation Methods

### ISSUE THREAD

**Issue by jly0810** [KAIST-Visual-AI-Group/PDS#6]
Your work provides two implementations based on nerf and 3DGS. Is there a difference in the effectiveness of these two methods? Which effect is better? What method was used to implement the results provided in your project webpage and paper?

**Comment by 63days** [comment]
Hi, jiy0810,

Thanks for your interest in our work.

We have observed that the editing outputs of PDS on both NeRF and 3DGS are quite similar, with both producing decent results. However, as 3DGS has fewer parameters, it offers faster runtime and reduced memory usage.

Unless we specifically mention that the results are from 3DGS, the results shown on our project webpage and in the paper are from NeRF.

Thanks,
Juil Koo
