### ISSUE TITLE
About 3D Editing Results

### ISSUE THREAD

**Issue by Kirito-Ausna** [KAIST-Visual-AI-Group/PDS#7]
Hi! Thanks for open sourcing your awesome work. I have tried out your 3d editing examples in your readme:
ns-train pds --data data/yuseung \
		--load-dir outputs/yuseung/nerfacto/2024-09-13_215316/nerfstudio_models/ \
		--pipeline.pds.src_prompt "a photo of a sks man" \
		--pipeline.pds.tgt_prompt "a photo of a sks SpiderMan" \
		--pipeline.pds.sd_pretrained_model_or_path data/yuseung_dreambooth \
		--machine.num-devices 1

Before this, I had downloaded the dreambooth ckpt and initialized the NeRF Scene. However, I got into two problems:
1. The training speed is very slow (~6 hours). My device is Nvidia A100 80G, it should be very fast (actually NeRF training completes within 20 mins). And I also tried Gaussian Splatting, it was also very slow, nearly the same with NeRF. I think something must go wrong with my trial.
2. The results are weird. It was expected to be similar with the result shown in your paper. However I got two weird results (Both NeRF and GS):
GS edited with pdsplat
![SpiderMan_pdsplat](https://github.com/user-attachments/assets/652feb3b-7f92-443d-a560-d30f245b770d)
NeRF edited with pds
![SpiderMan_pds](https://github.com/user-attachments/assets/1118f4fc-1ae0-4544-9d3a-906b345458b1)

Could you please help me to resolve these issues? Many Thanks!

**Comment by balabala932131** [comment]
hi, i get the same issue. have u solve it ?

**Comment by lyx0208** [comment]
similar results with same time cost

**Comment by 63days** [comment]
Hi, @Kirito-Ausna. Thanks for your interest in our work.

Although we mostly sample t within [0.02, 0.98], for some scenes where we expect more changes, we sample t within [0.1, 0.9]. The coefficient of the identity preservation term in the PDS equation, (x_0^tgt - x_0^src), increases exponentially 
 around t=0, so with a larger `pipeline.pds.min_step_ratio`, it can result in stronger changes. In our case, `min_step_ratio=0.1` was sufficient to achieve the desired changes. 

Regarding the speed of the editing process, it’s true that it takes some time, as each step requires encoding and decoding the rendered scene to pass the gradient through SD, which can be time-consuming. However, in our experience, 3DGS editing was about 3 to 4 times faster than NeRF editing. Also, if the input scene looks qualitatively well-adjusted in the intermediate steps, you can stop early. In the experiments for our paper, we set the number of steps to the maximum (=30k), but based on our experience, once the input scenes were sufficiently modified in the intermediate steps, running it further didn’t result in significant changes.

Thanks,
Juil Koo
